version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspace:cached
    
    # Sobrescreve o comando padrão para manter o container rodando
    command: sleep infinity
    
    # Portas expostas
    ports:
      - "8000:8000"
    
    # Variáveis de ambiente
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - PYTHONUNBUFFERED=1
    
    # Rede
    networks:
      - django-network

networks:
  django-network:
    driver: bridge

